#!/bin/zsh
set -euo pipefail

# Move to the repo root (one level up from tools/)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.." || {
  echo "Could not move to Vault root."
  exit 1
}

# Sanity check
if [[ ! -f "README.md" || ! -d "knowledge" ]]; then
  echo "[x] This script must be run from within vault/tools/. It auto-navigates to repo root."
  exit 1
fi

# Settings
INDEX_NAME="_index.yaml"
IGNORE_DIRS_REGEX="^\./(\.git|\.github|\.venv|__pycache__|tools)(/|$)"

# YAML content
INDEX_CONTENT=$(cat <<EOF
title: Vault Directory Index
description: >
  This is an autogenerated _index.yaml for structured browsing in the Vault repository.
tags: [vault, index, auto]
updated: $(date +%Y-%m-%d)
EOF
)

# Iterate
echo "[*] Starting _index.yaml injection..."
find . -type d | grep -Ev "$IGNORE_DIRS_REGEX" | while read dir; do
  INDEX_FILE="$dir/$INDEX_NAME"
  if [[ ! -f "$INDEX_FILE" ]]; then
    echo "[+] Creating: $INDEX_FILE"
    echo "$INDEX_CONTENT" > "$INDEX_FILE"
  fi
done

echo "[✓] All eligible directories now have _index.yaml"

